<a href="https://colab.research.google.com/github/afullhart/climateanalogs/blob/main/Colab/Score.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
%reset -f

In [2]:
!pip install rioxarray
!pip install rasterio
!pip install tifffile
!pip install imagecodecs

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.7/62.7 kB 2.2 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 22.3/22.3 MB 84.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 23.2/23.2 MB 66.6 MB/s eta 0:00:00


In [3]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [36]:
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import numpy as np
import geopandas as gpd
from sklearn.metrics import silhouette_samples, silhouette_score
import rasterio
import rioxarray as rx
from PIL import Image
import tifffile
import imagecodecs

comf = '/content/drive/My Drive/Colab Notebooks/Analogs/Extract_Composite.tif'
isof = '/content/drive/My Drive/Colab Notebooks/Analogs/IsoCluster.tif'

image = Image.open(isof)
arr = np.asarray(image)

print(arr)
print(arr.size)
print(arr.shape)

img_array = tifffile.imread(comf)
image = Image.fromarray(img_array[:, :, 0]).convert('L')
arr = np.asarray(image)

print(arr)
print(arr.size)
print(arr.shape)


[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 6 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
2615802
(1281, 2042)
[[255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255   0 ... 255 255 255]
 ...
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]
 [255 255 255 ... 255 255 255]]
2615802
(1281, 2042)
